// Generated by `npm run build:runtime` from verified files in source-parts/cursive-font.js.
// This repository intentionally stores large browser modules in compressed deterministic parts.
throw new Error('Связный движок ещё не собран. Выполните npm install && npm run build:runtime.');
